### ISSUE TITLE
Selecting "Back to Order" link on Add Payment Page yields error

### ISSUE THREAD

**Issue by tshavor** [NSS-Team-Delta/Bangazon-Initial-Site#132]
### Feature Description

From the Add Payment Page, click “Back to Order” link before entering payment information results in the page loading “http://localhost:5000/Order” with an error that the localhost page can’t be found… 

### Notes

**Comment by caseywreed** [comment]
This may be solved with #134 

Can you try reproducing this error on that PR feature branch? I suspect the problem is similar to the original issue in that PR: without an ActiveUser selected, the Order/Index method fails to return.

**Comment by caseywreed** [comment]
Nevermind. This was wrong. "Order" changed to "Orders"
